/*
 * CalculatorView.java
 */

   package calculator;

   import org.jdesktop.application.Action;
   import org.jdesktop.application.ResourceMap;
   import org.jdesktop.application.SingleFrameApplication;
   import org.jdesktop.application.FrameView;
   import org.jdesktop.application.TaskMonitor;
   import java.awt.event.ActionEvent;
   import java.awt.event.ActionListener;
   import javax.swing.Timer;
   import javax.swing.Icon;
   import javax.swing.JDialog;
   import javax.swing.JFrame;

/**
 * The application's main frame.
 */
    public class CalculatorView extends FrameView {
      public boolean plus = false;
      public boolean minus = false;
      public boolean multyply = false;
      public boolean division = false;
      public boolean fact = false;
      public boolean tmin = true;
      public boolean tdiv = true;
      String number = "";
      String temp = "";
      Double tans = 0.0,tmul = 1.0;
       public CalculatorView(SingleFrameApplication app) {
         super(app);
      
         initComponents();
      
        // status bar initialization - message timeout, idle icon and busy animation, etc
         ResourceMap resourceMap = getResourceMap();
         int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
         messageTimer = new Timer(messageTimeout, 
                new ActionListener() {
                   public void actionPerformed(ActionEvent e) {
                     statusMessageLabel.setText("");
                  }
               });
         messageTimer.setRepeats(false);
         int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
         for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
         }
         busyIconTimer = new Timer(busyAnimationRate, 
                new ActionListener() {
                   public void actionPerformed(ActionEvent e) {
                     busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                     statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
                  }
               });
         idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
         statusAnimationLabel.setIcon(idleIcon);
         progressBar.setVisible(false);
      
        // connecting action tasks to status bar via TaskMonitor
         TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
         taskMonitor.addPropertyChangeListener(
                new java.beans.PropertyChangeListener() {
                   public void propertyChange(java.beans.PropertyChangeEvent evt) {
                     String propertyName = evt.getPropertyName();
                     if ("started".equals(propertyName)) {
                        if (!busyIconTimer.isRunning()) {
                           statusAnimationLabel.setIcon(busyIcons[0]);
                           busyIconIndex = 0;
                           busyIconTimer.start();
                        }
                        progressBar.setVisible(true);
                        progressBar.setIndeterminate(true);
                     } 
                     else if ("done".equals(propertyName)) {
                        busyIconTimer.stop();
                        statusAnimationLabel.setIcon(idleIcon);
                        progressBar.setVisible(false);
                        progressBar.setValue(0);
                     } 
                     else if ("message".equals(propertyName)) {
                        String text = (String)(evt.getNewValue());
                        statusMessageLabel.setText((text == null) ? "" : text);
                        messageTimer.restart();
                     } 
                     else if ("progress".equals(propertyName)) {
                        int value = (Integer)(evt.getNewValue());
                        progressBar.setVisible(true);
                        progressBar.setIndeterminate(false);
                        progressBar.setValue(value);
                     }
                  }
               });
      }
   
       @Action
       public void showAboutBox() {
         if (aboutBox == null) {
            JFrame mainFrame = CalculatorApp.getApplication().getMainFrame();
            aboutBox = new CalculatorAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
         }
         CalculatorApp.getApplication().show(aboutBox);
      }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {
      
         mainPanel = new javax.swing.JPanel();
         jTextField1 = new javax.swing.JTextField();
         jButton1 = new javax.swing.JButton();
         jButton2 = new javax.swing.JButton();
         jButton3 = new javax.swing.JButton();
         jButton4 = new javax.swing.JButton();
         jButton5 = new javax.swing.JButton();
         jButton6 = new javax.swing.JButton();
         jButton7 = new javax.swing.JButton();
         jButton8 = new javax.swing.JButton();
         jButton9 = new javax.swing.JButton();
         jButton10 = new javax.swing.JButton();
         jButton11 = new javax.swing.JButton();
         jButton12 = new javax.swing.JButton();
         jButton13 = new javax.swing.JButton();
         jButton14 = new javax.swing.JButton();
         jButton15 = new javax.swing.JButton();
         jButton16 = new javax.swing.JButton();
         jButton17 = new javax.swing.JButton();
         jButton18 = new javax.swing.JButton();
         menuBar = new javax.swing.JMenuBar();
         javax.swing.JMenu fileMenu = new javax.swing.JMenu();
         javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
         javax.swing.JMenu helpMenu = new javax.swing.JMenu();
         javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
         statusPanel = new javax.swing.JPanel();
         javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
         statusMessageLabel = new javax.swing.JLabel();
         statusAnimationLabel = new javax.swing.JLabel();
         progressBar = new javax.swing.JProgressBar();
      
         org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(calculator.CalculatorApp.class).getContext().getResourceMap(CalculatorView.class);
         mainPanel.setBackground(resourceMap.getColor("Fram.background")); // NOI18N
         mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
         mainPanel.setName("Fram"); // NOI18N
         mainPanel.setPreferredSize(new java.awt.Dimension(400, 252));
      
         jTextField1.setEditable(false);
         jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
         jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
         jTextField1.setName("jTextField1"); // NOI18N
      
         jButton1.setText(resourceMap.getString("zero_btn.text")); // NOI18N
         jButton1.setName("zero_btn"); // NOI18N
         jButton1.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     zero_btn(evt);
                  }
               });
      
         jButton2.setText(resourceMap.getString("one_btn.text")); // NOI18N
         jButton2.setName("one_btn"); // NOI18N
         jButton2.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     one_btn(evt);
                  }
               });
      
         jButton3.setText(resourceMap.getString("two_btn.text")); // NOI18N
         jButton3.setName("two_btn"); // NOI18N
         jButton3.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     two_btn(evt);
                  }
               });
      
         jButton4.setText(resourceMap.getString("three_btn.text")); // NOI18N
         jButton4.setName("three_btn"); // NOI18N
         jButton4.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     three_btn(evt);
                  }
               });
      
         jButton5.setText(resourceMap.getString("four_btn.text")); // NOI18N
         jButton5.setName("four_btn"); // NOI18N
         jButton5.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     four_btn(evt);
                  }
               });
      
         jButton6.setText(resourceMap.getString("five_btn.text")); // NOI18N
         jButton6.setName("five_btn"); // NOI18N
         jButton6.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     five_btn(evt);
                  }
               });
      
         jButton7.setText(resourceMap.getString("six_btn.text")); // NOI18N
         jButton7.setName("six_btn"); // NOI18N
         jButton7.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     six_btn(evt);
                  }
               });
      
         jButton8.setText(resourceMap.getString("saven_btn.text")); // NOI18N
         jButton8.setName("saven_btn"); // NOI18N
         jButton8.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     saven_bn(evt);
                  }
               });
      
         jButton9.setText(resourceMap.getString("eight_btn.text")); // NOI18N
         jButton9.setName("eight_btn"); // NOI18N
         jButton9.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     eight_btn(evt);
                  }
               });
      
         jButton10.setText(resourceMap.getString("nine_btn.text")); // NOI18N
         jButton10.setName("nine_btn"); // NOI18N
         jButton10.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     nine_bnt(evt);
                  }
               });
      
         jButton11.setText(resourceMap.getString("div_btn.text")); // NOI18N
         jButton11.setName("div_btn"); // NOI18N
         jButton11.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     div_bn(evt);
                  }
               });
      
         jButton12.setText(resourceMap.getString("multy_btn.text")); // NOI18N
         jButton12.setName("multy_btn"); // NOI18N
         jButton12.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     multy_btn(evt);
                  }
               });
      
         jButton13.setText(resourceMap.getString("minus_btn.text")); // NOI18N
         jButton13.setName("minus_btn"); // NOI18N
         jButton13.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     minus_btn(evt);
                  }
               });
      
         jButton14.setText(resourceMap.getString("plus_btn.text")); // NOI18N
         jButton14.setName("plus_btn"); // NOI18N
         jButton14.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     plus_btn(evt);
                  }
               });
      
         jButton15.setText(resourceMap.getString("dot_btn.text")); // NOI18N
         jButton15.setName("dot_btn"); // NOI18N
         jButton15.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     dot_btn(evt);
                  }
               });
      
         jButton16.setText(resourceMap.getString("equal_btn.text")); // NOI18N
         jButton16.setName("equal_btn"); // NOI18N
         jButton16.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     equal_btn(evt);
                  }
               });
      
         jButton17.setText(resourceMap.getString("clear_btn.text")); // NOI18N
         jButton17.setName("clear_btn"); // NOI18N
         jButton17.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     clear_btn(evt);
                  }
               });
      
         jButton18.setText(resourceMap.getString("fact_btn.text")); // NOI18N
         jButton18.setName("fact_btn"); // NOI18N
         jButton18.addActionListener(
                new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                     fact_btn(evt);
                  }
               });
      
         javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
         mainPanel.setLayout(mainPanelLayout);
         mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            );
         mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton17))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16)
                    .addComponent(jButton18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
      
         mainPanel.getAccessibleContext().setAccessibleParent(null);
      
         menuBar.setName("menuBar"); // NOI18N
      
         fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
         fileMenu.setName("fileMenu"); // NOI18N
      
         javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(calculator.CalculatorApp.class).getContext().getActionMap(CalculatorView.class, this);
         exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
         exitMenuItem.setName("exitMenuItem"); // NOI18N
         fileMenu.add(exitMenuItem);
      
         menuBar.add(fileMenu);
      
         helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
         helpMenu.setName("helpMenu"); // NOI18N
      
         aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
         aboutMenuItem.setName("aboutMenuItem"); // NOI18N
         helpMenu.add(aboutMenuItem);
      
         menuBar.add(helpMenu);
      
         statusPanel.setBackground(resourceMap.getColor("statusPanel.background")); // NOI18N
         statusPanel.setFocusable(false);
         statusPanel.setName("statusPanel"); // NOI18N
      
         statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N
         statusPanel.add(statusPanelSeparator);
      
         statusMessageLabel.setName("statusMessageLabel"); // NOI18N
         statusPanel.add(statusMessageLabel);
      
         statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
         statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N
         statusPanel.add(statusAnimationLabel);
      
         progressBar.setEnabled(false);
         progressBar.setFocusable(false);
         progressBar.setName("progressBar"); // NOI18N
         progressBar.setRequestFocusEnabled(false);
         statusPanel.add(progressBar);
      
         setComponent(mainPanel);
         setMenuBar(menuBar);
         setStatusBar(statusPanel);
      }// </editor-fold>//GEN-END:initComponents
   
       private void zero_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zero_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "0";
         jTextField1.setText(number);
      }//GEN-LAST:event_zero_btn
   
       private void one_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "1";
         jTextField1.setText(number);
      }//GEN-LAST:event_one_btn
   
       private void two_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "2";
         jTextField1.setText(number);
      }//GEN-LAST:event_two_btn
   
       private void three_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_btn
        // TODO add your handling code here:
         number = jTextField1.getText() +"3";
         jTextField1.setText(number);
      }//GEN-LAST:event_three_btn
   
       private void four_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "4";
         jTextField1.setText(number);
      }//GEN-LAST:event_four_btn
   
       private void five_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "5";
         jTextField1.setText(number);
      }//GEN-LAST:event_five_btn
   
       private void six_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "6";
         jTextField1.setText(number);
      }//GEN-LAST:event_six_btn
   
       private void saven_bn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saven_bn
        // TODO add your handling code here:
         number = jTextField1.getText() + "7";
         jTextField1.setText(number);
      }//GEN-LAST:event_saven_bn
   
       private void eight_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_btn
        // TODO add your handling code here:
         number = jTextField1.getText() + "8";
         jTextField1.setText(number);
      }//GEN-LAST:event_eight_btn
   
       private void nine_bnt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_bnt
        // TODO add your handling code here:
         number = jTextField1.getText() + "9";
         jTextField1.setText(number);
      }//GEN-LAST:event_nine_bnt
   
       private void dot_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_btn
        // TODO add your handling code here:
         if(jTextField1.getText().contains("."))
            return;
         else
         {
            number = jTextField1.getText() + ".";
            jTextField1.setText(number);
         }
      }//GEN-LAST:event_dot_btn
   
       private void plus_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_btn
        // TODO add your handling code here:
         if(number == null)
            return;
         else
         {
            plus = true;
            op_plus();
         }
      }//GEN-LAST:event_plus_btn
   
       private void minus_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus_btn
        // TODO add your handling code here:
         if(number==null)
            return;
         else
         {
            minus = true;
            op_minus();
         }
      }//GEN-LAST:event_minus_btn
   
       private void multy_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multy_btn
        // TODO add your handling code here:
         if(number==null)
            return;
         else
         {
            multyply = true;
            op_multy();
         }
      }//GEN-LAST:event_multy_btn
   
       private void div_bn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_bn
        // TODO add your handling code here:
         if(number==null)
            return;
         else
         {
            division = true;
            op_div();
         }
      }//GEN-LAST:event_div_bn
   
       private void fact_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fact_btn
        // TODO add your handling code here:
         if(number==null)
            return;
         else
         {
            fact = true;
            temp = number;
            jTextField1.setText(null);
         }
      }//GEN-LAST:event_fact_btn
   
       private void equal_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_btn
        // TODO add your handling code here:
         try
         {
            if(plus)
            {
               Double ans = tans + Double.parseDouble(number);
               jTextField1.setText("" + ans);
               plus = false;
            }
            if(minus)
            {
               Double ans = tans - Double.parseDouble(number);
               jTextField1.setText("" + ans);
               minus = false;
            }
            if(multyply)
            {
               Double ans = tmul * Double.parseDouble(number);
               jTextField1.setText("" + ans);
               multyply = false;
            }
            if(division)
            {
               Double ans = tans / Double.parseDouble(number);
               jTextField1.setText("" + ans);
               division = false;
            }
            if(fact)
            {
               Long num = Long.parseLong(temp);
               long ans = 1;
               while(num>0)
               {
                  ans = ans*num;
                  num--;
               }
               jTextField1.setText("" + ans);
               fact = false;
            }
         }
             catch(Exception ex)
            {
               jTextField1.setText(ex.getMessage().toString());
            }
      }//GEN-LAST:event_equal_btn
   
       private void clear_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn
        // TODO add your handling code here:
         plus = minus = multyply = division = fact = false;
         tmin = tdiv = true;
         tans = 0.0;
         tmul = 1.0;
         number  = "";
         temp = "";
         jTextField1.setText(null);
      }//GEN-LAST:event_clear_btn
   
       private void op_plus()
      {
         temp = number;
         tans = tans + Double.parseDouble(temp);
         jTextField1.setText(null);
      }
       private void op_minus()
      {
         temp = number;
         Double x = Double.parseDouble(temp);
         if(tmin)
         {
            tans = x - tans;
            tmin = false;
         }
         else
         {
            tans = tans - x;
         }
         jTextField1.setText(null);
      }
   
       private void op_multy()
      {
         temp = number;
         tmul = tmul * Double.parseDouble(temp);
         jTextField1.setText(null);
      }
   
       private void op_div()
      {
         try
         {
            temp = number;
            Double x = Double.parseDouble(temp);
            if(tdiv)
            {
               tans = x;
               tdiv = false;
            }
            else
            {
               tans = tans / x;
            }
            jTextField1.setText(null);
         }
             catch(Exception ex)
            {
               jTextField1.setText(ex.getMessage());
            }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButton1;
      private javax.swing.JButton jButton10;
      private javax.swing.JButton jButton11;
      private javax.swing.JButton jButton12;
      private javax.swing.JButton jButton13;
      private javax.swing.JButton jButton14;
      private javax.swing.JButton jButton15;
      private javax.swing.JButton jButton16;
      private javax.swing.JButton jButton17;
      private javax.swing.JButton jButton18;
      private javax.swing.JButton jButton2;
      private javax.swing.JButton jButton3;
      private javax.swing.JButton jButton4;
      private javax.swing.JButton jButton5;
      private javax.swing.JButton jButton6;
      private javax.swing.JButton jButton7;
      private javax.swing.JButton jButton8;
      private javax.swing.JButton jButton9;
      private javax.swing.JTextField jTextField1;
      private javax.swing.JPanel mainPanel;
      private javax.swing.JMenuBar menuBar;
      private javax.swing.JProgressBar progressBar;
      private javax.swing.JLabel statusAnimationLabel;
      private javax.swing.JLabel statusMessageLabel;
      private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
   
      private final Timer messageTimer;
      private final Timer busyIconTimer;
      private final Icon idleIcon;
      private final Icon[] busyIcons = new Icon[15];
      private int busyIconIndex = 0;
   
      private JDialog aboutBox;
   }
